### ISSUE TITLE
"Enter Dojo" -> Blurry layer covers first card   &&   Button "Start session"

### ISSUE THREAD

**Issue by j-eick** [j-eick/vocab-dojo#23]
### Tasks 

- [x] Rename: Start Session -> Enter Dojo
- [x] Add blurry layer that covers first card
- [x] Add and place "Start Session" button on blurry layer
- [x] onClick of "Start Session", blurry layer goes away
