### ISSUE TITLE
Basic Style: Flashcards

### ISSUE THREAD

**Issue by j-eick** [j-eick/vocab-dojo#25]
### Tasks

- [x] Frontside: 
  - [x] Optional title field
  - [x] Description field

like so:
frontTitle: frontsideTitle,
frontText: frontsideText,

- [x] Backside: 
  - [x] Optional title field
  - [x] Description field 

like so:
backTitle: backsideTitle,
backText: backsideText,

Check these places:
- Services
- Model
- AddVocabForm

-------------------------------------------------------------

`Need to create 2 variants for <p>, one if <p> is alone and one <p> if there's also a <title>. Same for <title>.`

- [x] Conditional flashcard formatting:
  - [x] Frontside: if only title OR description ⬇️ 
![Image](https://user-images.githubusercontent.com/107850377/235550891-937b114c-78cf-44de-b098-d56c087dc88e.png)

  - [x] Backside: If title only, then only display in middle of card as normal text; 
                           If also description, then show like ⬇️
![Image](https://user-images.githubusercontent.com/107850377/235551801-cfdfaaa3-6d33-4474-87e3-699434d92a06.png)
