### ISSUE TITLE
Mongoose: DeleteAll, DeleteOne

### ISSUE THREAD

**Issue by j-eick** [j-eick/vocab-dojo#31]
### Task

- [x] DELETE ALL documents inside collection x
  - [x] List doesn't update after deleting all documents. Use either useState or globalState.
  - [x] implement globalState
  - [x] List of vocabs is passed to globalState
  - [x] card-element receives its data from globalState
  - [x] Deletebutton empties globalStateArray AND MongoDB

- [ ] DELETE ONE document inside collection x
