### ISSUE TITLE
implement "last added + hard to remember" textboxes

### ISSUE THREAD

**Issue by j-eick** [j-eick/vocab-dojo#39]
### Tasks

- [ ] Preview Boxes on mainscreen show last 5-7 words.
- [ ] Display of words inside box via flexbox
  - [ ] if word in one row is too long, it automatically slides to the next line
- [ ] Box has a a "show more" link, if there are more words than can be shown inside the box
