### ISSUE TITLE
Modal: Repeated Question

### ISSUE THREAD

**Issue by j-eick** [j-eick/vocab-dojo#49]
### Description

Modal shows up, when user wantes to delete all existing flashcards in the collection.

**Page: all_Vocabs**

### Tasks

- [x] Create Modal that shows up, when user click "remove all" button. 
- [x] Modal consists of Question, Delete-Button, Close-Button
- [ ] Modal can be closed via
  - [x] Close-Button
  - [ ] Tapping somewhere outside the modal

- [ ] Modal has 2 animations: fadeIn & fadeOut.
  - [x] fade in
  - [ ] fade out

### ERROR

Modal: fadeOut animation

When condition = true, Modal shows up with fadeIn animation.
When condition = false, Modal disappears without fadeOut animation.

**File:** `Modal/index.jsx` (line 103)
